# Site settings
permalink: none #/:categories/:title.html
title: DevBlog
#email: dj.famer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Блог обо всем на свете.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" #"http://devblogblog.com" # the base hostname & protocol for your site
twitter_username: famer
github_username:  famer

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "tags" 
    values:
      #permalink: none
      layout: "tag"
