# Site settings
permalink: :title.html #none #/:categories/:title.html
title: DevBlog
#email: dj.famer@gmail.com
description: "I am Timur Tatarshaov: web and mobile developer, writer and aestetic." #> # this means to ignore newlines until "baseurl:"

  #Блог обо всем на свете.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://famer.github.io" #"http://devblogblog.com" # the base hostname & protocol for your site
twitter_username: famer
#github_username:  famer

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" 
      type: "pages"
    values:
      hideFromNav: false
  -
    scope:
      path: "tags" 
    values:
      #permalink: none
      layout: "tag"
  -
    scope:
      path: "ru" 
    values:
      category: "ru"
gems:
  - jemoji
